[package]
name = "rust-bench"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "my_benchmark"
harness = false

[dependencies]
libc = "0.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
cc = "1.0"